### ISSUE TITLE
Multiple custom domains for gh-pages (GitHub Pages)

### ISSUE THREAD

**Issue by DanielJRaine** [ga-wdi-boston/outcomes-portfolio#3]
I'm having a problem where my DNS registrar/hosted zone provider (Amazon Route 53) does not like it when I have multiple custom domains/hosted zones pointing to my github pages route.

When I edit my CNAME to `<username>.github.io/<project-name>` things break and the URL does not resolve.

It works when my CNAME is `<username>.github.io` but this only allows me to attach one and only one custom domain for one and only one of my projects.

Any idea how to setup multiple custom domains for a single gh-pages account with multiple project sites?

This means that I can either have custom domains for my portfolio site or a single project, which is not preferable.

**Comment by DanielJRaine** [comment]
I was mistaken.  You can have multiple CNAMEs set to `<username>.github.io`, and I'm guessing gh-pages handles the redirect to your specific project path.

**Comment by jrhorn424** [comment]
This is very useful. Thanks @DanielJRaine!
