### ISSUE TITLE
Trying to deploy portfolio site

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/outcomes-portfolio#4]
I'm trying to deploy my portfolio site, but I'm getting a page not found error.

I used a basic router (like we learned about on Friday) to set it up. Could that have anything to do with why it's not working?

**Comment by jrhorn424** [comment]
Possibly. I can't know without a link to your portfolio, a description of the request you're trying to make, and where you think the error might be.

**Comment by jrhorn424** [comment]
Sorry, that wasn't clear.

> I can't know without a link to your portfolio

Your portfolio repository.

> a description of the request you're trying to make, 

The deployed portfolio link.

> and where you think the error might be.

You mentioned the router. Can you think of anything else in addition that you'd like me to look at?

**Comment by julie1013** [comment]
Oh my God... I'm embarrassed. There was a typo when I was trying to access the portfolio site. It's all good. Thanks though.
