### ISSUE TITLE
Weird errors when I'm trying to deploy my portfolio

### ISSUE THREAD

**Issue by julie1013** [ga-wdi-boston/outcomes-portfolio#5]
Repo: https://github.com/julie1013/portfolio
Deployed site:https://julie1013.github.io/portfolio/

I am getting the following errors when I go to my portfolio site after deployment:

```bundle.js:1 Uncaught ReferenceError: webpackJsonp is not defined(…)```

```julie1013.github.io/:6 GET https://julie1013.github.io/portfolio/vendor.bundle.js ```

**Comment by BenGitsCode** [comment]
@julie1013 Reference [this](https://github.com/ga-wdi-boston/game-project/issues/355) issue.

Antony discovered a bug in githubs gh pages deployment. This _should_ fix the issue.

If not, there are more deployment fixes from wdi-015's project 1 [issue queue](https://github.com/ga-wdi-boston/game-project/issues?utf8=%E2%9C%93&q=is%3Aissue%20deploy%20) that may help you.

If it's any comfort, you probably did everything right and github is the problem.

**Comment by julie1013** [comment]
Thanks, I made all the changes, but I'm still getting these errors though:

```
https://julie1013.github.io/portfolio/dependencies.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

```
2016-11-05 13:31:05.840 https://julie1013.github.io/portfolio/bundle.js Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by jrhorn424** [comment]
Works fine for me. Try resetting your cache.

**Comment by julie1013** [comment]
Awesome, it worked! Thanks! It's that rare moment when an issue is actually an easy fix!
